name: Catalog Sync

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
  schedule:
    - cron: '15 */3 * * *'
  workflow_dispatch:

# permissions:
  # contents: read

jobs:
  catalog-sync:
    runs-on: ${{matrix.operating-system}}

    strategy:
      fail-fast: true
      matrix:
        operating-system: [ubuntu-latest]
        php: [8.2]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Check for tailscale is working
        run:
          tailscale status

      - name: Execute tests
        run: vendor/bin/phpunit
