name: Tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 */3 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{matrix.operating-system}}

    strategy:
      fail-fast: true
      matrix:
        operating-system: [ubuntu-22.04, ubuntu-20.04]
        php: [8.1, 8.2, 8.3]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: check for hello.ts.net in netmap
        run:
          tailscale status | grep -q hello

      - name: Execute tests
        run: vendor/bin/phpunit
